// <auto-generated />
namespace ADO_Exam.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_gamemode_and_copiessold : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_gamemode_and_copiessold));
        
        string IMigrationMetadata.Id
        {
            get { return "202205050847082_add_gamemode_and_copiessold"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
