// <auto-generated />
namespace ADO_Exam.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_fk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_fk));
        
        string IMigrationMetadata.Id
        {
            get { return "202205050906372_fix_fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
